#!/usr/bin/env bash
#configure web-02 to be identical to web-01

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default;
sudo sed -i '/listen 80 default_server/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '46i error_page 404 /custom_404.html;' /etc/nginx/sites-available/default;
sudo service nginx restart
