#!/usr/bin/env bash
#Fixing container so that Nginx is running as the nginx user and  all active IPs on port 8080

sudo service nginx stop
sed -i 's/# user www-data;/\nuser nginx;/g' /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo service nginx restart
