#!/usr/bin/env bash
#Fixing container so that Nginx is running as the nginx user and  all active IPs on port 8080
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
